### ISSUE TITLE
Failed Action

### ISSUE THREAD

**Issue by bdougie** [bdougie/contributor.info#68]
The issue arises from the use of a deprecated version of the `actions/upload-artifact@v3` action, as indicated in the job logs. The current workflow uses this action in the step defined on [line 73](https://github.com/bdougie/contributor.info/blob/c522e74feeab42bf4e34775531536734549f9848/.github/workflows/generate-social-cards.yml#L73).

### Solution:
Update the workflow to use the latest version of the `actions/upload-artifact` action. The recommended version is `v4` or the latest available version based on the [deprecation notice](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).

### Updated Code:
Replace the following block in your workflow file:

```yaml
- name: Upload artifacts on failure
  if: failure()
  uses: actions/upload-artifact@v3
  with:
    name: social-card-logs
    path: |
      temp-social-cards/
      *.log
    retention-days: 7
```

With:

```yaml
- name: Upload artifacts on failure
  if: failure()
  uses: actions/upload-artifact@v4
  with:
    name: social-card-logs
    path: |
      temp-social-cards/
      *.log
    retention-days: 7
```

### Steps to Apply the Fix:
1. Edit the file at [`.github/workflows/generate-social-cards.yml`](https://github.com/bdougie/contributor.info/blob/c522e74feeab42bf4e34775531536734549f9848/.github/workflows/generate-social-cards.yml).
2. Make the above change and commit it to your repository.
3. Re-run the workflow to confirm the issue is resolved.

This update should fix the failure and ensure compatibility with the latest version of the `upload-artifact` action. Let me know if you need further assistance!
